sonar.projectKey=sirosfoundation_siros-verifier-app
sonar.organization=sirosfoundation

sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**
sonar.dart.coverage.reportPath=coverage/lcov.info
